services:
#  db:
#    image: postgres:12
#    environment:
#      - POSTGRES_DB=dpla_api
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
